#context-path: /app
#server:
#  port: 8189
#  servlet:
#    context-path: /app
#springdoc:
#
#  api-docs:h: /docs
#
#    pat
#  swagger-ui:
#    filter: true
#    tryItOutEnabled: true
#    path: /swagger

spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  flyway:
    enabled: true
    locations: "classpath:db/migration"
  datasource:
    url: jdbc:postgresql://localhost:8284/races
    password: mpu
    username: mpu
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  logging:
    level:
      ROOT: ERROR